- hosts: all
  vars:
       ansible_password: '$6$Vktv4WMaBDbCVL2H$tDhOivAjW3NLdNtBHBeK24jZA1VoJhMJ9Y5KcwPAXv6hwozF3CWd7GwteVLIQqgYCkKAZISoDK/JHZEu8vJ9W1'
  gather_facts: no
  remote_user: ansible
  become: true


  tasks:
  - name: Add a new user named ansible
    user:
       name: ansible
       shell: /bin/bash
       password: "{{ ansible_password }}"

  - name: Add ansible user to the sudoers
    copy:
         dest: "/etc/sudoers.d/ansible"
         content: "ansible  ALL=(ALL)  NOPASSWD: ALL"

  - name: Deploy SSH Key
    authorized_key: user=ansible
                    key="{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}"
                    state=present

  - name: Disable Password Authentication
    lineinfile:
          dest=/etc/ssh/sshd_config
          regexp='^PasswordAuthentication'
          line="PasswordAuthentication no"
          state=present
          backup=yes

  - name: Disable Root Login
    lineinfile:
          dest=/etc/ssh/sshd_config
          regexp='^PermitRootLogin'
          line="PermitRootLogin no"
          state=present
          backup=yes
    notify:
      - restart sshhandlers:

  - name: restart ssh
    service:
      name=sshd
      state=restarted


