- hosts: all
  tasks:
#  - name: Add repository
#    yum_repository:
#       name: config-manager --set-enabled fedora-cisco-openh264
#    become: yes

  - name: install the latest version of package
    package:
       name:
         - mozilla-openh264
         - gstreamer1-plugin-openh264
       state: latest
    become: yes


