- hosts: all
  tasks:
  - name: Add repository
    yum_repository:
       name: qemu-firmware-jenkins
       description: firmware for qemu, built by jenkins, fresh from git repos
       baseurl: https://www.kraxel.org/repos/jenkins/
       file: firmware
       gpgcheck: no
       enabled: yes
    become: yes

  - name: Install KVM-related Packages
    package:
       name:
       - "@virtualization"
       - "edk2.git-ovmf-x64"
       state: latest
    register: libvirtd
    become: yes

  - name: Add the user 'admin' with a specific primary group of 'libvirt'
    user:
       name: admin
       comment: "DIT admin"
       groups: libvirt
       append: yes
    become: yes

  - name: link /usr/libexec/qemu-kvm -> /usr/bin/qemu-kvm
    file:
       src:  /usr/bin/qemu-kvm
       dest: /usr/libexec/qemu-kvm
       owner: libvirt
       group: libvirt
       state: link
    become: yes

  - name:  start libvirtd
    service:
      name: libvirtd
      state: started
    become: yes

  - name:  restart libvirtd
    service:
      name: libvirtd
      state: restarted
    when: libvirtd.changed
    become: yes


  - name: Disable SELinux
    selinux:
       state: disabled
    become: yes


#  - name: Put SELinux in permissive mode, logging actions that would be blocked.
#    selinux:
#       policy: targeted
#       state: permissive
#    become: yes
